project_id = "shjmqbtmkbmkintxibzn"

[functions.send-contact-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-freebie-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.send-automation-emails]
verify_jwt = false
